CREATE TABLE IF NOT EXISTS `admin`(
	'AID' int (11) NOT NULL AUTO_INCREMENT,
	'ANAME' varchar (150) NOT NULL,
	'APASS' varchar (150) NOT NULL,
	PRIMARY KEY ('AID')
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;